sudo: required
services:
  - docker

before_script: echo $docker-password

script:
  - docker build -t fsegall/node-ci .
  - docker images fsegall/node-ci

before_deploy:
  - docker login -u fsegall -p $docker-password 

deploy:
  provider: script
  script: docker push fsegall/node-ci
  on:
    branch: master
