sudo: required
services:
  - docker

script:
  - docker build -t fsegall/nodeCI .
  - docker images fsegall/nodeCI

# before_deploy:
#   - docker login -u <username>  -p <userpassword>

# deploy:
#   provider: script
#   script: docker push fsegall/nodeCI
#   on:
#     branch: master
